collections:
  timelapse:
    output: true

pagination:
  enabled: true
  per_page: 10
  category: 'blog'
  sort_field: 'date'
  sort_reverse: true

# whitelist:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-gist
#   - jekyll-feed
#   - jemoji

name: "blendertube"
description: "links to vetted, fantastic blender tutorials "

safe:        false
watch:       false    # deprecated
server:      false    # deprecated
host:        0.0.0.0
port:        4000
# baseurl:     /
# url:         https://localhost:4000

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blendertube.com" # the base hostname & protocol for your site
include: [.nojekyll]

permalink: /:categories/:title/
highlighter: pygments

enable_coderay         : true
syntax_highlighter     : coderay
syntax_highlighter_opts: {}

strict_front_matter: true

# coderay:
#   coderay_wrap: div
#   coderay_line_numbers: inline
#   coderay_line_numbers_start: 1
#   coderay_tab_width: 4
#   coderay_bold_every: 10
#   coderay_css: style

lsi: false
source: .

markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
textile_ext:   textile

excerpt_separator: "\n\n"

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  parse_block_html: true

redcloth:
  hard_breaks: true
